project:
    name: weread
    author: wxy

server:
  port: 8080

spring:
    # 生产/开发环境配置 需要有application-dev.yml/application-prod.yml
    profiles:
        active: dev
    #在Springboot中可以直接在配置文件中覆盖默认的静态资源路径的配置信息：
#    mvc:
    # static-path-pattern: /we/**   如果添加自定义目录，所有引用静态资源的地方都应添加
#        static-path-pattern: /**
    # spring.http.multipart.location 自定义的属性，指定了一个路径,上传物理路径；
    http:
        multipart:
            location: F://WereadTest
           #location: C://workProject/WereadTest
    #在这里配置静态资源路径，前面说了这里的配置是覆盖默认配置，所以需要将默认的也加上
    #否则static、public等这些路径将不能被当作静态资源路径，
    #在这个最末尾的file:${...}之所有要加file:是因为指定的是一个具体的硬盘路径，
    #其他的使用classpath指的是系统环境变量
#    resources:
#        static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/, file:${spring.http.multipart.location}

    datasource:
        name: weread
        url: jdbc:mysql://127.0.0.1:3306/weread
        username: root
        password: 123456
        # 使用druid数据库连接池
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    #thymeleaf
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
        #开发时关闭缓存,不然没法看到实时页面
    #消息中间件ActiveMQ
    activemq:
        broker-url: tcp://localhost:61616
        #broker-url: failover:(tcp://localhost:61616,tcp://localhost:61617)
        close-timeout: 5000
        in-memory: false
        send-timeout: 3000
        pool:
             max-connections: 100
#         pool:enabled: true  #如果此处设置为true，需要加如下的依赖包，否则会自动配置失败，报JmsMessagingTemplate注入失败
    #Spring boot默认使用的是SimpleCacheConfiguration，即使用ConcurrentMapCacheManager来实现缓存。
    #但是要切换到其他缓存实现也很简单
    #ehcache配置
    cache:
        type: ehcache
        ehcache:
           config: classpath:config/ehcache.xml #ehcache配置文件地址
    redis: #redis基础配置
        database: 5 # Redis数据库索引（默认为0）        host: 127.0.0.1
        port: 6379
        password:  # Redis服务器连接密码（默认为空）
        timeout: 3000 # 连接超时时间 单位 ms（毫秒）
        pool: #redis线程池设置
            max-idle: 10 # 连接池中的最大空闲连接，默认值也是8。
            min-idle: 5 #连接池中的最小空闲连接，默认值也是0。
            max-active: 2000 # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
            max-wait: 1000 # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
#        sentinel: #redis哨兵设置 主从复制
#            master: master8026 # Redis服务器master的名字
#            nodes: 10.189.80.25:26379,10.189.80.26:26379,10.189.80.27:26378 # redis-sentinel的配置地址和端口
#        cluster: #集群模式
    data:
         mongodb:  #NoSQL数据库
             uri: mongodb://localhost:27017/FirstTest
    application:
         name: weread
#######################################################################
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.wxy.model
#  configLocation: classpath:config/mybatis-config.xml
#  configuration:
#          #指定日志框架
#          logImpl: log4

#mybatis分页插件-pagehelper
pagehelper:
    helperDialect: mysql
    #分页参数合理化,默认是false
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql


